### ISSUE TITLE
ERROR in index.js

### ISSUE THREAD

**Issue by Amitesh92** [mschwarzmueller/reactjs-basics#11]
ERROR in ./src/app/index.js
Module build failed: Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\React-project\react-demo\node_modules\babel-loader\lib\index.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (D:\React-project\react-demo\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (D:\React-project\react-demo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\React-project\react-demo\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (D:\React-project\react-demo\node_modules\webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (D:\React-project\react-demo\node_modules\webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (D:\React-project\react-demo\node_modules\webpack\lib\Compilation.js:146:10)
    at moduleFactory.create (D:\React-project\react-demo\node_modules\webpack\lib\Compilation.js:433:9)
    at factory (D:\React-project\react-demo\node_modules\webpack\lib\NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (D:\React-project\react-demo\node_modules\webpack\lib\NormalModuleFactory.js:99:14)
    at D:\React-project\react-demo\node_modules\tapable\lib\Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (D:\React-project\react-demo\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\React-project\react-demo\node_modules\tapable\lib\Tapable.js:208:13)
    at resolver (D:\React-project\react-demo\node_modules\webpack\lib\NormalModuleFactory.js:74:11)
    at process.nextTick (D:\React-project\react-demo\node_modules\webpack\lib\NormalModuleFactory.js:205:8)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by Evokoo** [comment]
Add  the babel-core module to your project

`npm install babel-core --save-dev`
