### ISSUE TITLE
Error on "npm start"

### ISSUE THREAD

**Issue by sonakshisaxena1** [mschwarzmueller/reactjs-basics#22]
I am getting the following error when I type `npm start ` in terminal"

`ERROR in Entry module not found: Error: Can't resolve './src' in '/Users/sona/Documents/reactjs-basics'`

![screen shot 2018-03-30 at 1 31 46 am](https://user-images.githubusercontent.com/24795489/38110724-307b2110-33ba-11e8-8e33-8aee47d42e6c.png)

**Comment by nick-gibb** [comment]
Yeah, I'm getting the same.

**Comment by imtiaz-emu** [comment]
@sonakshisaxena1 , @nick-gibb Could you please upload your `webpack.config.js` file? In `webpack.config.js` file **loaders** option have been replaced with **rules**. Hope it helps!

**Comment by MegazeroMZ** [comment]
@sonakshisaxena1 @nick-gibb  "loaders" is deprecated, use "Rule.use" instead. Also on a side note I think you can use a different dependency called "babel-preset-env" instead of es2015 since its kinda old

**Comment by MaheshK02** [comment]
I am getting the following error when I type npm start in terminal"


｢config｣: An error occurred while trying to find a config file
              Did you forget to specify a --require?
/opt/reactjs-basics/node_modules/@webpack-contrib/config-loader/lib/load.js:84
    throw new LoadConfigError(e, configPath);
    ^

LoadConfigError: SRC_DIR is not defined
    at Object.<anonymous> (/opt/reactjs-basics/webpack.config.js:7:9)
    at Module._compile (/opt/reactjs-basics/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/opt/reactjs-basics/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadJs (/opt/reactjs-basics/node_modules/cosmiconfig/dist/loaders.js:8:18)
    at Explorer.loadFileContent (/opt/reactjs-basics/node_modules/cosmiconfig/dist/createExplorer.js:226:12)

**Comment by shuvo0074** [comment]
@MegazeroMZ @imtiaz-emu , can you give an example on how to use Rule.use ??

**Comment by MegazeroMZ** [comment]
@shuvo0074 something like this

`module: { 
        rules: [ 
            {
                use: [
                  {
                    loader: "babel-loader",
                    query: {
                        presets: ["env", "react", "stage-2"] 
                    }
                  }
                ]
            }
        ]
    }`

**Comment by shuvo0074** [comment]
@MegazeroMZ  Where to put these two lines? 
test: /\.js?/,
include: SRC_DIR,

otherwise my components in js files are not loading.

**Comment by hitu4233** [comment]
I am also getting same issues.

**Comment by shuvo0074** [comment]
@hitu4233 ,
1. Instead of babel-preset-es2015, npm install "babel-preset-env"
2. In webpack.config.js , write "rules" instead of "loaders"
3. in package.json , replace "cp" with "copyfiles" at line 8 and 9.
These things solved my problems in windows platform.
Or you can fork this repository:  https://github.com/shuvo0074/React.js-initial to start a new project, all issues are solved and all packages are included.

**Comment by nitinprajapati** [comment]
@sonakshisaxena1 @nick-gibb Are you using windows? If yes then change the forward slashes(/) to backward slashes(\\) in package.json file, also change the cp command to copy and try. Let me know for further issue.

**Comment by martinandersen3d** [comment]
[Click here for solution - https://github.com/mschwarzmueller/reactjs-basics/issues/25](https://github.com/mschwarzmueller/reactjs-basics/issues/25)
